### ISSUE TITLE
Could “TopK + ConE” selection strategy be used to API-only LLM？ 

### ISSUE THREAD

**Issue by Siki-cloud** [Romainpkq/revisit_demon_selection_in_ICL#1]
Hi, I found the methodology you used to be reasonable and robust.   But I am curious if this approach can also be applied to closed-source LLMs?

**Comment by Romainpkq** [comment]
Since our method needs to calculate the conditional entropy of the test input,  it cannot currently be applied to closed-source LLMs where output probs are unavailable.
